### ISSUE TITLE
Goal event hook issue returned?

### ISSUE THREAD

**Issue by Chronuid** [AaronVickers/FriendlyReminders#1] opened 2024-03-27 10:51 UTC
heyheyy  - I recently started to use your "friendly reminders"-Plugin and I really like it. Its pretty cool. But unfortunately its not showing me the reminders if a goal is shot. Only after the game. I tried everything, but nothing seems to work :/ - So I thought either the goal event hook issue got with the newest update in RL back or I am too dumb to use the plugin correctly xD

**Comment by AaronVickers** [comment] 2024-04-07 18:31
Hey, thanks for bringing this to my attention! I'm glad you're liking the plugin, despite this current lack in functionality.
It looks like this was caused by a change in behaviour of the `gameWrapper->IsInGame` function.
https://github.com/AaronVickers/friendly-reminders/blob/2774797c70fda8a33be870d48d23bc6aa85828d8/FriendlyReminders.cpp#L183
I'll address this shortly.

**Comment by AaronVickers** [comment] 2024-04-07 19:15
Fixed in the latest release.

**Closed as completed by AaronVickers** 2024-04-07 19:15 UTC
